### ISSUE TITLE
Move to Jekyll

### ISSUE THREAD

**Issue by SolalPirelli** [LauzHack/LauzHack.github.io#10]
Currently this website is a big HTML page. This is rather annoying when we need to add content, because we end up copy/pasting a ton of stuff, such as markup for sponsors or organizers.

GitHub Pages supports Jekyll, which is a simple site generator. One can declare collections of items, and include them in a page with templates. Let's use that instead.

- [x] Decide on what the website should contain (something more/less than currently?)
- [ ] Decide on the rough shape of the website (keep one page? add a few for less-used stuff?)
- [x] Decide on schemas for all data (e.g. what exactly is a person? name, picture, website, ...?)
- [x] Migrate data to the new schemas in Jekyll-compatible format
- [x] Write the new website's templates

**Comment by SolalPirelli** [comment]
Schema ideas:

**Person**
- First name
- Last name
- Picture
- Website

This is currently what we have. An open question is what size/ratio the picture should have, since we want it to look good on high-DPI. We could also add people's titles... should we emphasize who the president/VP/treasurer are?

**FAQ item**
- ID
- Title
- Description

ID is so we can refer to items in a link - we had that requirement for the "intellectual property" FAQ item, some companies don't want their employees to do stuff in hackathons if you don't clarify which IP they will produce.

**Past years**
- Year
- Picture
- Links to the photos taken during the event
- Description (e.g. "in our first edition, the winner did XYZ...")

This would be a new item (instead of the unstructured description we have at the top of the page right now).

**Sponsor**
- Name
- Picture
- Link

We need the name for an alt text of the picture. I think it'll be easier to have each sponsor tier as a separate collection - but I don't know much Jekyll; is there a way to group by tier and then 1) order the tiers in a specific way (not alphabetical) 2) set image size depending on the tier without having to repeat it on all elements?

**Comment by Arbaba** [comment]
The schemas look good.  Maybe we should emphasize people's title but also show what everyone is working on (logistics, sponsoring, IT etc)? So that we have a clear presentation of the committee.

Here are some ideas for the Sponsor issues
1. If we add  'tier-name' and 'tier-priority' values to the sponsor, it is pretty easy to sort them by priority and group by name using [sort and group_by filters](https://learn.cloudcannon.com/jekyll-cheat-sheet/). We can then output each tier in the right order with a for-loop.

2. In the actual code all sponsors in the same tier are surrounded by a `<div class="sponsor-gold/silver.."` where the CSS class handles all the size and color work. With Jekyll, we can just append the tier-name variable resulting from the group_by instead of hard-coding it.

 Having both variables is a bit redundant. It might be possible to simplify this but sorting with Jekyll seems limited: I'm not sure we can easily sort a collection according to an operation on the elements (e.g correspondence between a tier-name and tier-priority/id ). Have to check that.

**Comment by SolalPirelli** [comment]
Thanks for the comments!

I think that with data files (https://jekyllrb.com/docs/datafiles/), we can do this kind of "lookup" for tiers - see the example "accessing a specific author". So we'd have a list of tiers, and then a file with the display name and priority of each tier. Yay!

**Comment by SolalPirelli** [comment]
I've pushed a _data folder, more to come... :)

**Comment by SolalPirelli** [comment]
Done, sponsors were easier than I thought. Still need a link to a page with the association's statutes and GA meetings.

**Comment by SolalPirelli** [comment]
Done.
