### ISSUE TITLE
Create registration website

### ISSUE THREAD

**Issue by SolalPirelli** [LauzHack/LauzHack.github.io#12]
Not really an issue for this specific repo (can't do dynamic pages with GitHub Pages anyway), but this is for brainstorming.

We need participants to:

- Tell us their name, t-shirt size, etc.
- Tell us their location, to know how much travel reimbursement they can get
  - this is more difficult than it sounds since we need to agree on categories with the whole committee, and on well-defined boundaries (is Finland part of Europe, despite the high flight costs? what about Turkey?)
- Group into teams
  - last year we had people form teams or request to join an existing one, which was confusing; at HC2 I made a website where you had to send an invite to others to join your team, it seems to work a lot better
  - however, need some way to prevent people from registering twice with different emails otherwise they get confused

As a bonus, we could have project submission directly on the website, but that's for later I guess.

What do y'all think? Do we need something more? Is there a specific way we should do something?

**Comment by sourabhlal** [comment]
- We need a pre-registration page (just taking names and email addresses). Last time we used a google form, but it will be easier during the pre-registration round so that we dont have to manually verify if they pre-registered or not.

- The things you listed are all ok for the main application form. I don't see anything missing

- After they are accepted and are eligible for travel reimbursement then we need a place for them to upload their travel proof.

- Can we use the MailChimp API to send the emails this time? They are much prettier :P

**Comment by SolalPirelli** [comment]
@sourabhlal Thanks! Re: your point 1, IMHO it's no big deal if someone registers during the early period without having pre-registered - especially if e.g. somebody who had pre-registered tells their friends about it. We just don't make the link itself public for a week or so. Or do you think it's important to let only pre-registered people register?

**Comment by sourabhlal** [comment]
That's a good point - as long as the link isn't public and we just email them the application link it should be fine.
